version: '2'
services:
  ghanaweb:
    image: ghananauticalinfo/ghanaweb:1.0.0
    links:
      - mysqldb:db
      - couchdb:couch
    ports: 
      - "8080:8080"
      - "8443:8443"
    depends_on: 
      - mysqldb
      - couchdb
    volumes: 
      - ~$USER/ghanaweb/properties:/opt/jboss/wildfly/ghanaweb_properties
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: embryo
      MYSQL_PASSWORD: embryo
      MYSQL_DATABASE: embryo
  couchdb:
    image: dmadk/embryo-couchdb
    volumes:
      - ~$USER/ghanaweb/couchdb:/data

